CREATE TABLE IF NOT EXISTS 
products(
    product_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    brand VARCHAR(100) NOT NULL,
    image_url VARCHAR(200),
    price INTEGER NOT NULL,
    category VARCHAR(100),
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
)

CREATE TABLE IF NOT EXISTS
reviews(
    review_id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    comment VARCHAR(300) NOT NULL,
    rate INTEGER NOT NULL,
    product_id INTEGER REFERENCES products (product_id),
    created_at TIMESTAMPTZ DEFAULT NOW()
)